// src/client/app/components/authentication/Login/Login.tsx
import React, { useState } from 'react';
import { withRouter, RouteComponentProps } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { bindActionCreators } from 'redux';
import { Formik, Field, ErrorMessage, Form } from 'formik';
import * as Yup from 'yup';

import { createLogin } from '@store/authentication/actions';
import ClosableError from '@components/shared/ClosableError/ClosableError';
import { LoginRequestDto } from '@interfaces/user.interface';

import './Login.css';

const SignupSchema = Yup.object().shape({
    email: Yup.string()
        .email('Please enter a valid email address')
        .required('Please enter your email address'),
    password: Yup.string()
        .required('Please enter your password')
});

const Login: React.FunctionComponent<RouteComponentProps> = (props) => {
    const [error, setError] = useState<null | string>(null);
    const dispatch = useDispatch();

    const loginRequest = bindActionCreators(
        {
            submit: createLogin
        },
        dispatch
    );

    function clearError(): void {
        setError(null);
    }

    function submitForm(values: LoginRequestDto): Promise<void> {
        return loginRequest.submit(values)
            .then(() => {
                props.history.push('/');
            })
            .catch(() => {
                setError('Unable to log you in. Please check your credentials and try again.');
            });
    }

    return (
        <div className='column is-three-quarters is-offset-2 Login'>
            <h1 className='title'>Login</h1>
            <h3 className='subtitle'>Welcome back to MBU Online!</h3>
            {
                error &&
                (
                    <ClosableError
                        message={error}
                        messageClosed={clearError}
                    />
                )
            }
            <Formik
                initialValues={{
                    email: '',
                    password: ''
                } as LoginRequestDto}
                validationSchema={SignupSchema}
                onSubmit={submitForm}
            >
                {({
                    isSubmitting,
                    errors,
                    touched,
                }) => (
                    <Form>
                        <div className='field'>
                            <label
                                htmlFor='email'
                                className='label'
                            >
                                Email
                            </label>
                            <div className='control'>
                                <Field
                                    type='email'
                                    name='email'
                                    className={`input is-expanded ${touched.email && errors.email && 'is-danger'}`}
                                    placeholder='Enter your email'
                                />
                            </div>
                            <ErrorMessage
                                name='email'
                                component='span'
                                className='help is-danger'
                            />
                        </div>
                        <div className='field'>
                            <label
                                htmlFor='password'
                                className='label'
                            >
                                Password
                            </label>
                            <div className='control'>
                                <Field
                                    type='password'
                                    name='password'
                                    className={`input is-expanded ${touched.password && errors.password && 'is-danger'}`}
                                    placeholder='Password'
                                />
                            </div>
                            <ErrorMessage
                                name='password'
                                component='span'
                                className='help is-danger'
                            />
                        </div>
                        <div className='field is-grouped button-bar'>
                            <div className='control'>
                                <button
                                    type='submit'
                                    className={`button is-primary ${isSubmitting ? 'is-loading' : ''}`}
                                    disabled={isSubmitting}
                                >
                                    Login
                                </button>
                            </div>
                            <div className='control'>
                                <button
                                    type='button'
                                    className='button is-info is-outlined'
                                    disabled={isSubmitting}
                                    onClick={() => props.history.push('/signup')}
                                >
                                    Create an account
                                </button>
                            </div>
                            <div className='control reset-control'>
                                <button
                                    type='button'
                                    className='button is-text'
                                    disabled={isSubmitting}
                                    onClick={() => props.history.push('/reset')}
                                >
                                    Forgot your password?
                                </button>
                            </div>
                        </div>
                    </Form>
                )}
            </Formik>
        </div>
    );
};

export default withRouter(Login);

// src/client/src/components/authentication/Login.vue
<template>
  <div>
    <div class="column is-three-quarters is-offset-2">
      <h1 class="title">Login</h1>
      <h3 class="subtitle">Welcome back to MBU Online!</h3>
      <div class="notification is-warning"
           v-if="error">
        <button class="delete"
                @click.prevent="dismissError()"></button>
        <p>Invalid email/password combination</p>
      </div>
      <div class="notification is-success"
           v-if="$route.query.from === 'resetSuccess'">
        <p>
          Successfully reset your password! Please login to your account with using new password.
        </p>
      </div>
      <form>
        <div class="field">
          <label class="label"
                 for="login-email">Email</label>
          <div class="control">
            <input type="email"
                   class="input is-expanded"
                   id="login-email"
                   placeholder="Enter your email"
                   :class="{ 'is-danger': $v.credentials.email.$error }"
                   @blur="$v.credentials.email.$touch"
                   v-model="credentials.email">
          </div>
          <span v-if="$v.credentials.email.$error">
            <span class="help is-danger"
                  v-if="!$v.credentials.email.email">
              Email address is invalid
            </span>
            <span class="help is-danger"
                  v-if="!$v.credentials.email.required">
              Email is required
            </span>
          </span>
        </div>
        <div class="field">
          <label class="label"
                 for="login-password">Password</label>
          <div class="control">
            <input type="password"
                   class="input is-expanded"
                   id="login-password"
                   placeholder="Password"
                   :class="{ 'is-danger': $v.credentials.password.$error }"
                   @blur="$v.credentials.password.$touch"
                   v-model="credentials.password">
          </div>
          <span class="help is-danger"
                v-if="!$v.credentials.password.required && $v.credentials.password.$error">
            Password is required
          </span>
        </div>
        <br>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-primary"
                    :class="{ 'is-loading': loading }"
                    :disabled="$v.credentials.$invalid || loading"
                    @click.prevent="submit()">Login</button>
          </div>
          <div class="control">
            <button class="button is-info is-outlined"
                    :disabled="loading"
                    @click.prevent="signup()">Create an Account</button>
          </div>
          <div class="control">
            <router-link class="button is-text is-pulled-right"
                         :disabled="loading"
                         to="/reset">Forgot your password?</router-link>
          </div>
        </div>
        <br>
      </form>
    </div>
  </div>
</template>

<script>
import { required, email } from 'vuelidate/lib/validators'

export default {
  data () {
    return {
      credentials: {
        email: '',
        password: ''
      },
      error: false,
      loading: false
    }
  },
  methods: {
    dismissError () {
      this.$v.$reset();
      this.error = '';
    },
    submit () {
      let credentials = {
        email: this.credentials.email,
        password: this.credentials.password,
      }

      this.loading = true;
      this.$store.dispatch('login', credentials)
        .then(() => {
          this.error = false;
          this.$router.push('/');
        })
        .catch(() => {
          this.error = true;
        })
        .then(() => {
          this.loading = false;
        });
    },
    signup () {
      this.$emit('close');
      this.$router.push('/signup');
    },
    reset () {
      this.$emit('close');
      this.$router.push('/reset');
    }
  },
  validations: {
    credentials: {
      email: {
        required,
        email
      },
      password: {
        required
      }
    }
  }
}
</script>

<style scoped lang="scss">
a {
  cursor: pointer;
}
</style>
